CONFIG:
  [
    {
      'id': 1,
      'name': '背景',
      'directory': 'bj',
      'required': True,
      'rarity_weights': None,
    },
    {
      'id': 2,
      'name': '武器',
      'directory': 'wq',
      'required': True,
      'rarity_weights': None,
    },
    {
      'id': 3,
      'name': '主体',
      'directory': 'zt',
      'required': True,
      'rarity_weights': None,
    },
    {
      'id': 4,
      'name': '服饰',
      'directory': 'fs',
      'required': True,
      'rarity_weights': None,
    },
    {
      'id': 5,
      'name': '帽子',
      'directory': 'mz',
      'required': True,
      'rarity_weights': None,
    },
  ]
drop_dup: True
# CONFIG_JSON_NAME: "Greek-Mythical-Panda#"
# CONFIG_JSON_URL: "https://ipfs.io/ipfs/Qmd56C6tsi4SAzzMwhZDGogsUAZfzBXd6BX2BX5gmNwhew"
# CONFIG_JSON_DESCRIPTION: "The Greek Mythical Panda is a collection of 100 NFT digital identities with accessory backgrounds generated entirely from random seeds. Let you experience random art."